apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.configmap.name" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  {{- if .Values.web.config }}
    {{- if .Values.web.config.openApiYaml }}
    openapi.yaml: |
      {{- .Values.web.config.openApiYaml | nindent 6 }}
    {{- end }}
    {{- if .Values.web.config.aiPluginJson }}
    ai-plugin.json: |
      {{- .Values.web.config.aiPluginJson | toJson | nindent 6 }}
    {{- end }}
  {{- end }}
